### ISSUE TITLE
"Error: Cannot find module '@sls-next/next-aws-cloudfront'" when running serverless with serverless-next.js

### ISSUE THREAD

**Issue by Shadrack1701** [serverless-nextjs/serverless-next.js#481] opened 2020-07-01 15:20 UTC
When either local or it github actions our serverless command now always fails when deploying with the error:
 Error: Cannot find module '@sls-next/next-aws-cloudfront'

For me to reproduce this I can run npx serverless in github pipeline or locally.

To deploy the next js application to aws stack.

Here is the error from github, same as what I get locally:
```
error:
  Error: Cannot find module '@sls-next/next-aws-cloudfront'
Require stack:
- /home/runner/.serverless/components/registry/npm/serverless-next.js@1.15.0-alpha.2/node_modules/@sls-next/lambda-at-edge/dist/build.js
- /home/runner/.serverless/components/registry/npm/serverless-next.js@1.15.0-alpha.2/node_modules/@sls-next/lambda-at-edge/dist/index.js
- /home/runner/.serverless/components/registry/npm/serverless-next.js@1.15.0-alpha.2/node_modules/serverless-next.js/serverless.js
- /home/runner/work/injury-claim-express-web/injury-claim-express-web/app/node_modules/@serverless/core/src/Component.js
- /home/runner/work/injury-claim-express-web/injury-claim-express-web/app/node_modules/@serverless/core/src/index.js
- /home/runner/work/injury-claim-express-web/injury-claim-express-web/app/node_modules/serverless/node_modules/@serverless/cli/src/index.js
- /home/runner/work/injury-claim-express-web/injury-claim-express-web/app/node_modules/serverless/lib/components-v1.js
- /home/runner/work/injury-claim-express-web/injury-claim-express-web/app/node_modules/serverless/bin/serverless.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.resolve (internal/modules/cjs/helpers.js:78:19)
    at Builder.<anonymous> (/home/runner/.serverless/components/registry/npm/serverless-next.js@1.15.0-alpha.2/node_modules/@sls-next/lambda-at-edge/dist/build.js:119:49)
    at Generator.next (<anonymous>)
    at /home/runner/.serverless/components/registry/npm/serverless-next.js@1.15.0-alpha.2/node_modules/@sls-next/lambda-at-edge/dist/build.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/runner/.serverless/components/registry/npm/serverless-next.js@1.15.0-alpha.2/node_modules/@sls-next/lambda-at-edge/dist/build.js:4:12)
    at Builder.buildDefaultLambda (/home/runner/.serverless/components/registry/npm/serverless-next.js@1.15.0-alpha.2/node_modules/@sls-next/lambda-at-edge/dist/build.js:98:16)
    at Builder.<anonymous> (/home/runner/.serverless/components/registry/npm/serverless-next.js@1.15.0-alpha.2/node_modules/@sls-next/lambda-at-edge/dist/build.js:266:24)
    at Generator.next (<anonymous>) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
      '/home/runner/.serverless/components/registry/npm/serverless-next.js@1.15.0-alpha.2/node_modules/@sls-next/lambda-at-edge/dist/build.js',
    '/home/runner/.serverless/components/registry/npm/serverless-next.js@1.15.0-alpha.2/node_modules/@sls-next/lambda-at-edge/dist/index.js',
    '/home/runner/.serverless/components/registry/npm/serverless-next.js@1.15.0-alpha.2/node_modules/serverless-next.js/serverless.js',
    '/home/runner/work/injury-claim-express-web/injury-claim-express-web/app/node_modules/@serverless/core/src/Component.js',
    '/home/runner/work/injury-claim-express-web/injury-claim-express-web/app/node_modules/@serverless/core/src/index.js',
    '/home/runner/work/injury-claim-express-web/injury-claim-express-web/app/node_modules/serverless/node_modules/@serverless/cli/src/index.js',
    '/home/runner/work/injury-claim-express-web/injury-claim-express-web/app/node_modules/serverless/lib/components-v1.js',
    '/home/runner/work/injury-claim-express-web/injury-claim-express-web/app/node_modules/serverless/bin/serverless.js'
  ]
}
25h
  38s › injury-claims-express › Error: Cannot find module '@sls-next/next-aws-cloudfront'
Require stack:
- /home/runner/.serverless/components/registry/npm/serverless-next.js@1.15.0-alpha.2/node_modules/@sls-next/lambda-at-edge/dist/build.js
- /home/runner/.serverless/components/registry/npm/serverless-next.js@1.15.0-alpha.2/node_modules/@sls-next/lambda-at-edge/dist/index.js
- /home/runner/.serverless/components/registry/npm/serverless-next.js@1.15.0-alpha.2/node_modules/serverless-next.js/serverless.js
- /home/runner/work/injury-claim-express-web/injury-claim-express-web/app/node_modules/@serverless/core/src/Component.js
- /home/runner/work/injury-claim-express-web/injury-claim-express-web/app/node_modules/@serverless/core/src/index.js
- /home/runner/work/injury-claim-express-web/injury-claim-express-web/app/node_modules/serverless/node_modules/@serverless/cli/src/index.js
- /home/runner/work/injury-claim-express-web/injury-claim-express-web/app/node_modules/serverless/lib/components-v1.js
- /home/runner/work/injury-claim-express-web/injury-claim-express-web/app/node_modules/serverless/bin/serverless.js
```
Here are my dependencies in my package.json:
```json
  "dependencies": {
    "amazon-cognito-identity-js": "^4.3.1",
    "aws-sdk": "^2.521.0",
    "axios": "^0.19.2",
    "dayjs": "^1.8.28",
    "jose": "^1.27.1",
    "next": "^9.4.4",
    "next-connect": "^0.7.1",
    "prop-types": "^15.7.2",
    "qrcode.react": "^1.0.0",
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "react-hook-form": "^5.7.2",
    "react-icons": "^3.10.0",
    "react-tabs": "^3.1.1",
    "react-toastify": "^6.0.5",
    "serverless-next.js": "^1.14.0",
    "yup": "^0.29.1"
  },
  "devDependencies": {
    "@testing-library/jest-dom": "^5.10.1",
    "@testing-library/react": "^10.4.1",
    "@zeit/next-css": "^1.0.1",
    "chance": "^1.1.6",
    "dotenv": "^8.1.0",
    "dotenv-webpack": "^1.8.0",
    "jest": "^26.1.0",
    "msw": "^0.19.4",
    "postcss-preset-env": "^6.7.0",
    "serverless": "^1.51.0",
    "tailwindcss": "^1.4.6"
  }
```
and here is my serverless.yml file:
```yml
app-name:
  component: serverless-next.js
  inputs:
    bucketName: app-s3
    name: App-Lambda
    nextStaticDir: ./src
```

And to be clear I am doing these steps in order each time:
npm i
npm test
next build
npx serverless

Any help would be greatly appreciated

**Comment by danielcondemarin** [comment] 2020-07-01 15:22
Duplicate of https://github.com/serverless-nextjs/serverless-next.js/issues/480

**Closed by danielcondemarin** 2020-07-01 15:22 UTC
Labels: triage

**Comment by Shadrack1701** [comment] 2020-07-01 15:23
@danielcondemarin thanks for the quick response!  Sorry I didn't see that one.
