### ISSUE TITLE
Separate build and deploy phases

### ISSUE THREAD

**Issue by kprzybylo** [serverless-nextjs/serverless-next.js#1633] opened 2021-09-03 09:21 UTC
**Is your feature request related to a problem? Please describe.**
Currently there is option to disable build phase, which will result in taking already existing build to the deploy.
What I am missing is to allow executing only build without deploy.

**Describe the solution you'd like**
Additional method like 'serverless build' to perform only build of a project. It could have additional parameter pointing to configuration for the build, default would be 'serverless.yml'. 'serverless' would use it under the hood. That way configuration from serverless.yml could allow to disable build in 'serverless' while building project with e.g. 'serverless build build-config.yml' would be possible.

**Describe alternatives you've considered**
Since framework is using @sls-next/lambda-at-edge to perform build it's not possible to use classic next build methods.
Reproducing the build phase using lambda-at-edge is also very hard, a lot of error happens.

**Comment by dphang** [comment] 2021-09-03 18:53
Actually there is with `deploy` boolean input: https://github.com/serverless-nextjs/serverless-next.js/commit/5adaf2bacae6f8647ac7fc90f910eefb97d8f229 but I think I missed documenting it. Will add the docs later. Does it work for you?

**Comment by kprzybylo** [comment] 2021-09-06 07:45
Great, that is what I was looking for. Would be great to have it in documentation.

**Comment by dphang** [comment] 2021-09-08 00:17
Yup it's already documented. Will close this since the issue is resolved.

**Closed** 2021-09-08 00:17 UTC
