### ISSUE TITLE
Deploying with the CDK (or plain Cloudformation)

### ISSUE THREAD

**Issue by plumdog** [serverless-nextjs/serverless-next.js#311] opened 2020-03-10 14:18 UTC
**Is your feature request related to a problem? Please describe.**
I'm not using the serverless framework, I'm using the CDK. I want to be able to deploy a next.js app to APIGateway/Lambda/S3. I think that this project will help me to do that, but I'm not sure how.

**Describe the solution you'd like**
An overview of how I might go about generating code using this project and what things need to be deployed to AWS to make the app work.

**Describe alternatives you've considered**
I have tried using https://github.com/vincent-herlemont/next-aws-lambda-webpack-plugin, which has generated a lambda per page (and a shared lambda layer), but to make it work I need to traverse the lambda directories it creates, and determine the APIGateway config for it. I've also found that for the index route, I get an error like:
```
TypeError: Cannot read property 'match' of null
    at renderReqToHTML (/var/task/index.js:25929:30)
    at Module.render (/var/task/index.js:26000:28)
```
Further, one lambda per page seems unnecessary (at least, I'm not sure what the advantages are), though I'm happy to be told it is best practice. 

**Additional context**
None. Happy to put together an example repo if that would be helpful.

**Comment by plumdog** [comment] 2020-03-10 23:58
I think I have identified this as an issue in next.js - see https://github.com/zeit/next.js/pull/10953

**Comment by danielcondemarin** [comment] 2020-03-11 08:20
@plumdog I’ve started working on support for aws-cdk (see https://github.com/danielcondemarin/serverless-next.js/tree/aws-cdk-support) although is still in progress so don’t expect it to work. 

In terms of one lambda per page or not, I plan to provide the same architecture as the [next component](https://github.com/danielcondemarin/serverless-next.js/tree/master/packages/serverless-nextjs-component), that is SSR and API pages deployed to Lambda@Edge and static pages to S3 so there wouldn’t be API gateway. Later on, I may add the ability to deploy api gateway backed by one lambda per page (like the [next plugin](https://github.com/danielcondemarin/serverless-next.js/tree/master/packages/serverless-nextjs-plugin)). The central idea is to give users building blocks (aka [Constructs in CDK](https://docs.aws.amazon.com/cdk/latest/guide/constructs.html)) they can use to design and deploy their next app however they want. 

I’m hoping to create a formal RFC with the official proposal.

**Comment by plumdog** [comment] 2020-03-12 11:17
Per https://github.com/zeit/next.js/pull/10953, the issue is not with next.js, but rather with the value set for `req.url` here https://github.com/danielcondemarin/serverless-next.js/blob/8da92e2d8e23e361c24904e4579e9d4e02845126/packages/next-aws-lambda/lib/compatLayer.js#L15-L18

This is definitely a separate issue to my original CDK question, so I'll create a separate issue. But, fwiw, a way of dodging this issue is to put Cloudfront in front of API Gateway - Cloudfront defaults to route the "default" object, ie, the thing you get when you access the domain with no path, to `/index.html`. So provided you make API Gateway respond to `/index.html`, nothing from Cloudfront will ever encounter this error.

**Comment by OFranke** [comment] 2020-04-04 06:43
Hey @danielcondemarin!
Would you mind giving a little more context on what needs to be done to make the whole thing work via CDK? In form of tickets, todos, an architecture diagram?

I just jumped into CDK and plan to somehow bring my nextjs frontend to AWS. I will do it any way, not sure how exactly yet - but this here seems like a good chance to make a useful contribution.

I'd appreciate some guidance by you :)

**Comment by danielcondemarin** [comment] 2020-05-02 21:42
> Hey @danielcondemarin!
> Would you mind giving a little more context on what needs to be done to make the whole thing work via CDK? In form of tickets, todos, an architecture diagram?
> 
> I just jumped into CDK and plan to somehow bring my nextjs frontend to AWS. I will do it any way, not sure how exactly yet - but this here seems like a good chance to make a useful contribution.
> 
> I'd appreciate some guidance by you :)

Hi @OFranke ! Sorry it took me so long to reply to this. If you're still interested in contributing I can put together a summary of what needs doing? Thanks!

**Comment by OFranke** [comment] 2020-05-21 03:34
Sorry @danielcondemarin, didn’t check my mentions. I’d be happy to take care of that. Will take me some time though but I am working on a production infrastructure that’s definitely going to be optimized regarding cost of hosting at some point. Right now I just hosted the nextjs app as ECS Container via cdk which is for sure not the best way to do.

**Comment by plumdog** [comment] 2020-05-22 10:17
Something to beware regarding this is https://github.com/aws/aws-cdk/issues/3463

Each CDK asset contributes 3 parameters, and there's a maximum of 60 in a Cloudformation stack, so that's a limit of 20.

This puts some constraints on the one-lambda-per-page architecture, until that issue is solved. I think the answer here is probably to wait for CDK to resolve that limitation. However, in the meantime, I think would require using a single shared (large) asset is used by all Lambdas, which is not ideal.

**Comment by danielcondemarin** [comment] 2020-05-22 10:39
> Something to beware regarding this is https://github.com/aws/aws-cdk/issues/3463
> 
> 
> 
> Each CDK asset contributes 3 parameters, and there's a maximum of 60 in a Cloudformation stack, so that's a limit of 20.
> 
> 
> 
> This puts some constraints on the one-lambda-per-page architecture, until that issue is solved. I think the answer here is probably to wait for CDK to resolve that limitation. However, in the meantime, I think would require using a single shared (large) asset is used by all Lambdas, which is not ideal.

@plumdog The architecture I am planning to go for is using [Lambda@Edge and CloudFront](https://github.com/danielcondemarin/serverless-next.js/blob/master/README.md#architecture). That should be well under the limit of CloudFormation resources. Yes it means all server side rendered pages in one Lambda but that’s fine, the next.js team released a new build target optimised for this use 🙂
Later on I’d like to support API Gateway + Lambda like the plugin but using the  new build target.

**Comment by plumdog** [comment] 2020-05-22 11:44
> the next.js team released a new build target optimised for this use

@danielcondemarin What build target is this? Only "server" and "serverless" are listed here https://nextjs.org/docs/api-reference/next.config.js/build-target and I am hopeful it could help with my API Gateway + Lambda assets problem.

**Comment by danielcondemarin** [comment] 2020-05-22 19:51
> > the next.js team released a new build target optimised for this use
> 
> @danielcondemarin What build target is this? Only "server" and "serverless" are listed here https://nextjs.org/docs/api-reference/next.config.js/build-target and I am hopeful it could help with my API Gateway + Lambda assets problem.

The target is still experimental, you can see the PR for it [here],(https://github.com/zeit/next.js/pull/8246). That's probably why is not listed in the docs. 
Although is experimental is actually what Vercel Now uses under the hood as you can see [here](https://github.com/zeit/now/blob/master/packages/now-next/src/index.ts#L807). 
The difference between "serverless" and "serverless-trace" is that the latter doesn't bundle `node_modules` for each page bundle, instead which leads to less code duplication therefore smaller lambda artefacts. To support the target in a project like this, you need to pack the `node_modules` manually and uploading them to Lambda so they're available during SSR. I have added support for it on the nextjs component, currently released on the latest alpha. See https://github.com/danielcondemarin/serverless-next.js/issues/236#issuecomment-629866977.

**Comment by dbartholomae** [comment] 2020-07-12 00:07
Any progress here? This topic affects me as well and I might have some time to help with a PR or two :)

**Comment by elendirx** [comment] 2020-07-24 19:04
We used serverless framework heavily at work and it served us well, but `serverless-components` looks more like a desperate monetization attempt with no real benefit.

I would like to create similar architecture with CDK. Where to start? Should I just pick up the [old branch](https://github.com/serverless-nextjs/serverless-next.js/tree/aws-cdk-support) or do we have more recent code?

**Comment by asterikx** [comment] 2020-08-06 10:51
> @plumdog I’ve started working on support for aws-cdk (see https://github.com/danielcondemarin/serverless-next.js/tree/aws-cdk-support) although is still in progress so don’t expect it to work.

@danielcondemarin the link doesn't work anymore. I'm very interested in this too. Is there any progress?

**Comment by asterikx** [comment] 2020-08-10 20:11
I checked the link again, and today it works. Weird.

Anyways @danielcondemarin let me know if you need any help with the CDK stuff.

I have seen the `NextjsConstruct` [here](https://github.com/serverless-nextjs/serverless-next.js/blob/aws-cdk-support/packages/cdk/NextjsConstruct.ts) (I'll probably define my own, since I need additional origins for API GW, AppSync, and my CMS).

To generate the handler code, I followed the instructions from the [`lambda-at-edge` package](https://github.com/serverless-nextjs/serverless-next.js/tree/master/packages/libs/lambda-at-edge#usage).

I created a script:

```js
// generate-handlers.js

const path = require('path');
const { Builder } = require('@sls-next/lambda-at-edge');

const nextConfigDir = __dirname; // '/dir/to/my/nextapp';
const outputDir = path.join(nextConfigDir, '.serverless_nextjs');

const builder = new Builder(nextConfigDir, outputDir, {
  cmd: './node_modules/.bin/next',
  cwd: process.cwd(),
  env: {},
  args: ['build']
});

(async function () {
  return await builder.build();
})();
```

and then invoked it using `node generate-handlers.js` from the root of my Next.js app.

After creating the folder structure, the script just hangs and nothing happens. Do you have any idea what could be causing this?

**Comment by luismanuel001** [comment] 2020-09-17 11:09
@danielcondemarin can we get an update on this? I'm also very interested on this, and may be able to help with it depending on the plan and current progress of this.

**Comment by GerardKetuma** [comment] 2020-10-06 19:55
> I checked the link again, and today it works. Weird.
> 
> Anyways @danielcondemarin let me know if you need any help with the CDK stuff.
> 
> I have seen the `NextjsConstruct` [here](https://github.com/serverless-nextjs/serverless-next.js/blob/aws-cdk-support/packages/cdk/NextjsConstruct.ts) (I'll probably define my own, since I need additional origins for API GW, AppSync, and my CMS).
> 
> To generate the handler code, I followed the instructions from the [`lambda-at-edge` package](https://github.com/serverless-nextjs/serverless-next.js/tree/master/packages/libs/lambda-at-edge#usage).
> 
> I created a script:
> 
> ```js
> // generate-handlers.js
> 
> const path = require('path');
> const { Builder } = require('@sls-next/lambda-at-edge');
> 
> const nextConfigDir = __dirname; // '/dir/to/my/nextapp';
> const outputDir = path.join(nextConfigDir, '.serverless_nextjs');
> 
> const builder = new Builder(nextConfigDir, outputDir, {
>   cmd: './node_modules/.bin/next',
>   cwd: process.cwd(),
>   env: {},
>   args: ['build']
> });
> 
> (async function () {
>   return await builder.build();
> })();
> ```
> 
> and then invoked it using `node generate-handlers.js` from the root of my Next.js app.
> 
> After creating the folder structure, the script just hangs and nothing happens. Do you have any idea what could be causing this?
> 
> EDIT: turns out I had commented `args: ['build']`, which causes `next` to start the development server instead creating a built.

@asterikx Did you get it to work? I'm planning on going down this path.

**Comment by asterikx** [comment] 2020-10-06 20:01
@GerardKetuma Yes and no. My setup worked, but I abandoned it due to unacceptable cold start times (which were likely caused by my project dependencies)

**Comment by crash7** [comment] 2020-10-11 04:04
@danielcondemarin any way I can give a hand with this? I was planning on building something like this (nextjs + cdk) but with AG and Cloudfront, as a side project using the base packages of this project.
Maybe I can also contribute to your efforts towards cdk? 
Let me know!

**Comment by dphang** [comment] 2020-11-03 03:50
If you use `deploy: false` input running `serverless` command will just build all outputs into the `.serverless_nextjs` directory, but not deploy, so you could actually use it with your own IaC like CDK or CDK for Terraform, you'd just need to manually provision the infrastructure yourselves (with all cache behaviors, etc.) from the build outputs.

We are looking into possibly migrating the deployment to CDK for Terraform (or other IaC) to solve a couple of pain points we've seen so far. Stay tuned.

**Comment by simonireilly** [comment] 2020-11-03 19:05
That's really promising. 

Looking at the existing branch there are a few Todo comments around cdk bundling.

This aws blog shows bundling for a static Nuxt.Js site. This could take care of managing the `serverless --component<component> build` step on synth/deploy.

https://aws.amazon.com/blogs/devops/building-apps-with-aws-cdk/

Then setting up the asset paths for S3 artefacts will be very straight forward as @dphang points out the `src` will be in the outdir.

CDK will be a nice API for customizing the stack without developing abstraction over Cloudfront, looking forward to progress.

**Comment by simonireilly** [comment] 2020-11-05 13:13
Here is an example with the CDK which has worked for me:

https://github.com/simonireilly/nextjs-aws-cdk, would be happy to feed into https://github.com/serverless-nextjs/serverless-next.js/tree/aws-cdk-support if it is still under development @danielcondemarin, @dphang ?

This deploys well for me, but you know, it won't reach the speed of a serverless component due to cloud formation restrictions >> https://d3a8vzm1ccycvj.cloudfront.net/

**Comment by apoorvmote** [comment] 2020-11-21 08:40
I am also looking to deploy Nextjs with CDK and/or cloudformation. I am new to this so please bare with me. 
Can we deploy Nextjs (with SSR) without @sls-next/lambda-at-edge? Also why are we using lambda@edge for SSR and API? In both cases the datasource is stored at single location e.g. Dynamodb Table at us-east-1. So what is the advantage if with lambda@edge vs lambda@us-east-1?

I have been using HTTP API instead of Rest API and deploying with CDK. And HTTP API cannot be at edge location but they are performing very good from single us-east-1 location. I am also looking for possiblity of SSR with HTTP API.

**Comment by dphang** [comment] 2021-05-22 06:02
I think this can be resolved since we have (experiment) CDK construct which has been implemented, so you can try that and hopefully it makes managing all the resources easier and more configurable.

For other issues like using Lambda@Edge vs. Lambda, I think that was original design and unfortunately the core code has been coupled with lambda-at-edge over the years. However we are working to decouple it so it can be platform-agnostic and work with Lambda/Cloudflare Workers/etc. in the near future.

**Closed by dphang** 2021-05-22 06:02 UTC
