### ISSUE TITLE
404 page not working for nested routes

### ISSUE THREAD

**Issue by afenton90** [serverless-nextjs/serverless-next.js#972] opened 2021-03-29 11:37 UTC
### Describe the bug
I have a Next.js app with a custom `pages/404.tsx` file. When accessing a route on the root of the domain that I expect to return a 404, this page renders fine (a.k.a `domain.com/broken-url`). However, when trying to access nested routes under this that should return the 404 page, the default Next.js 404 template is shown instead (a.k.a `domain.com/broken/this`)

### Expected behavior
When testing this using `npm run build` and `npm run start` the expected behaviour of rendering the custom 404 page works.

### Steps to reproduce
1. Create custom `/pages/404.tsx`
2. Deploy using this component.
3. Access `domain.com/broken-url` you will see the custom 404 page
4. Access `domain.com/broken/thisl` you will NOT see the custom 404 page

### Versions

- OS/Environment: Mac OS Big Sur
- @sls-next/serverless-component version: 1.18.0
- Next.js version: 10.0.9

### Checklist

- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by mdsavian** [comment] 2021-04-12 13:06
I'm facing the same issue.
I have a custom 404 page, and I'm not redirected to this page.
I'm using 
@sls-next/serverless-component: 1.19.0-alpha.43
next: 10.1.2

**Comment by dphang** [comment] 2021-04-15 05:05
Strange, I tried locally on the e2e next-app but could not reproduce the issue (using Big Sur). See below:

This is using the latest 1.19.0-alpha.43 version. Created a `404.tsx` page with this content:

```tsx
export default function Custom404() {
  return <h1>Custom 404</h1>;
}
```

and tested these URLs:

https://d1s0c4beiphe7z.cloudfront.net/unmatched/nested
https://d1s0c4beiphe7z.cloudfront.net/unmatched

Both of them render the custom 404 page. Could anyone add a full repro repository?

**Comment by afenton90** [comment] 2021-04-30 12:10
Don't know if this helps but I'm also getting the same behaviour with `@sls-next/cdk-construct` @dphang will continue to investigate.

**Comment by Reiiya** [comment] 2021-06-04 00:03
I ran into issue that 404.tsx do not work with `notFound: true`, but otherwise nested page errors work just fine (latest version).

**Comment by Reiiya** [comment] 2021-06-04 00:14
For me nested routes totally work on latest releases as well. Its just that `notFound: true` somehow does not work as redirect to 404. But it seems that it is next.js issue, because I can reproduce this locally.

**Comment by dphang** [comment] 2021-06-09 22:12
Sounds good, then I think we can close this issue if the latest issues are with Next.js itself

**Closed by dphang** 2021-06-09 22:12 UTC
