### ISSUE TITLE
useServerlessTraceTarget - Style class names are mismatched when deployed using this flag

### ISSUE THREAD

**Issue by develop-stuartohare** [serverless-nextjs/serverless-next.js#484] opened 2020-07-02 09:10 UTC
Hi, I'm experiencing some problems when deploying using the useServerlessTraceTarget flag in my serverless.yml.

"@material-ui/core": "^4.11.0",
"next": "^9.4.4",
"serverless": "^1.73.1",        
"serverless-next.js": "1.15.0-alpha.0",

When running locally, material-ui classNames - for example "makeStyles-test-1",  are correctly represented in the rendered style elements as head->style-> .makeStyles-test-1 but when deployed with useServerlessTraceTarget:true elements have "makeStyles-test-1" but the head style uses something like .jss1. Conversely, when deployed without useServerlessTraceTarget set both styles are correctly called .jss1

Any help greatly appreciated.

Thanks

**Comment by lone-cloud** [comment] 2020-07-02 15:46
Have you already followed https://material-ui.com/styles/advanced/#next-js ?

**Comment by develop-stuartohare** [comment] 2020-07-06 09:08
Hi, thanks for the reply.

Yes I have followed the documentation as per the link provided. 

I can deploy without using the useServerlessTraceTarget flag and classnames in style tag and in components/elements are in sync. But deploying with useServerlessTraceTarget : true they are not.

I'm testing this against a very simple codebase with _app.js/_document.js & index.js pages and no next.config.js.

SSR of style sheets is working correctly but once the #jss-server-side style element is removed I loose all styles (when deployed with useServerlessTraceTarget).

To repeat - styles/classnames work correctly (i.e .jss_123) when deployed without useServerlessTraceTarget flag set in the serverless.yml

Thanks

**Comment by dphang** [comment] 2020-08-12 07:41
I'm also using MaterialUI with this target and found the same issue - class names are mismatched.

For example, I have a search bar with class `makeStyles-searchBar-14`, but the CSS uses `jss14`. But after doing a client-side navigation, e.g going to another page the style gets fixed.

I guess it has something to do with that `_document.js` file (in https://material-ui.com/styles/advanced/#next-js): https://github.com/mui-org/material-ui/blob/master/examples/nextjs/pages/_document.js. It seems when building with `useServerlessTraceTarget` on, it doesn't get built into the `.next` directory?

I saw the commit from NextJS team for `experimental-serverless-trace` (https://github.com/vercel/next.js/commit/b31c29673019da75fa8beec097282c1446c8d197#diff-9bca36b2a6a56b47a1e0d17550b54a39R98), it seems `_document.js` does not get output to the build directory with this new target. Perhaps a workaround is to include the same logic from another file?

**Comment by dphang** [comment] 2020-08-12 23:07
I think I figured out the problem, thanks to a semi-related issue in MaterialUI: https://github.com/mui-org/material-ui/issues/17423.

Turns out I had to set `NODE_ENV=production` in my `.env` file so when Next builds (e.g via Serverless), it can set this as an env variable. Then MaterialUI uses it to determine whether to use the `productionPrefix` (by default it's `jss`) when generating class names.

Here is the relevant code in MaterialUI:

https://github.com/mui-org/material-ui/blob/master/packages/material-ui-styles/src/createGenerateClassName/createGenerateClassName.js#L68-L79

The problem before: without this and with this `useServerlessTraceTarget` turned on, the classNames are generated with `jss` prefix on client side but in the actual server-response, it's using the development class name (e.g makeStyles-xxx-n). If i inspected the initial server response, the styles are all rendered correctly (all development class names). 

But when the HTML is loaded, the client will remove all the injected JSS styles (if you followed MaterialUI's integration guide with Next, that's what this code does: https://github.com/mui-org/material-ui/blob/master/examples/nextjs/pages/_app.js#L13-L16) and reinject its own JSS styles with the `jss` prefix.

This fix of setting `NODE_ENV=production` should make it so that the server response uses `jss` prefix for class names as well.

Without `useServerlessTraceTarget`, I did see that both client and server class names had `jss` prefix. So I think this is actually a gotcha in Next, not a problem 

**Bonus** 

If you want your own custom class name prefix, you can follow https://github.com/mui-org/material-ui/issues/17423 to generate the same one on both client and server side. It involves editing both `_app` and `_document` files with a custom `generateClassNames` function.

@develop-stuartohare hope this helps!

**Comment by dphang** [comment] 2020-08-31 05:14
Closing this issue as it should resolve, feel free to comment if the steps above didn't work :)

**Closed by dphang** 2020-08-31 05:14 UTC

**Comment by paleite** [comment] 2020-09-12 00:47
I can't seem to get this to work no matter how I add the env variable `NODE_ENV=production`.
On every page that uses `getServerSideProps` or `getInitialProps` I get `makeStyles` instead of `jss`. Could you upload a copy of your implementation, @dphang ?

**Comment by dphang** [comment] 2020-09-12 01:05
Sure, here's a snippet:

_app.tsx (not complete)

```ts
export default function App(
  props: AppProps
): JSX.Element | null {
  const { Component, pageProps } = props;
  const router = useRouter();

  useEffect(() => {
    // Remove the server-side injected CSS.
    const jssStyles = document.querySelector("#jss-server-side");
    if (jssStyles && jssStyles.parentElement !== null) {
      jssStyles.parentElement.removeChild(jssStyles);
    }
  }, []);

  // Fix up class names
  const generateClassName = createGenerateClassName({
    productionPrefix: "a",
  });

  // Return the normal page
  return (
    <StylesProvider generateClassName={generateClassName}>
      <UserContextProvider
        authenticated={authenticated}
        authDone={authDone}
        theme={theme}
      >
        <ThemeProvider>
          <Layout
            scrollToTop={pageProps.scrollToTop}
            title={pageProps.title}
            showCookiesBanner={showCookiesBanner}
          >
            <Component {...pageProps} />
          </Layout>
        </ThemeProvider>
      </UserContextProvider>
    </StylesProvider>
  );
}
```

_document.tsx

```ts
import React from "react";
import Document, { Head, Main, NextScript } from "next/document";
import {
  ServerStyleSheets,
  createGenerateClassName,
} from "@material-ui/core/styles";

export default class MyDocument extends Document {
  render(): JSX.Element {
    return (
      <html lang="en">
        <Head />
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    );
  }
}

MyDocument.getInitialProps = async (ctx) => {
  // Resolution order
  //
  // On the server:
  // 1. app.getInitialProps
  // 2. page.getInitialProps
  // 3. document.getInitialProps
  // 4. app.render
  // 5. page.render
  // 6. document.render
  //
  // On the server with error:
  // 1. document.getInitialProps
  // 2. app.render
  // 3. page.render
  // 4. document.render
  //
  // On the client
  // 1. app.getInitialProps
  // 2. page.getInitialProps
  // 3. app.render
  // 4. page.render

  // Render app and page and get the context of the page with collected side effects.
  const generateClassName = createGenerateClassName({
    productionPrefix: "a",
  });
  const sheets = new ServerStyleSheets({
    serverGenerateClassName: generateClassName,
  });

  const originalRenderPage = ctx.renderPage;

  ctx.renderPage = () =>
    originalRenderPage({
      enhanceApp: (App) => (props) => sheets.collect(<App {...props} />),
    });

  const initialProps = await Document.getInitialProps(ctx);

  return {
    ...initialProps,
    // Styles fragment is rendered after the app and page rendering finish.
    styles: [
      ...React.Children.toArray(initialProps.styles),
      sheets.getStyleElement(),
    ],
  };
};
```

Check to make sure the page bundle has inlined NODE_ENV=production` environment variable. For me I am using `.env` file which Next.js will inline as part of its build. I believe you can search for something similar.:

```ts
    processEnv([{"path":".env","contents":"NODE_ENV=production\n"}])
```

**Comment by paleite** [comment] 2020-10-13 12:23
Thanks, @dphang . This really helped me pin my problem down and I got it working eventually.

It was completely unrelated (a component didn't support SSR), but having your example allowed me to find the other issue more easily.

**Comment by Stupidism** [comment] 2021-09-14 08:39
I've got into this bug, too. Here's the online test link: https://jerry-ui-content-484-engineering.stage.getjerry.com/

As I debugged, the first render of material UI Box styles is right. The got wrong after the SSR css is removed.

The `MuiBox-root-4` should be replaced by `jss-4` on the client-side, which is not.

![image](https://user-images.githubusercontent.com/5801015/133224684-f2110a50-761d-45de-aae5-d315700b0a85.png)

The working example is our prod env:  https://getjerry.com/

![image](https://user-images.githubusercontent.com/5801015/133224934-6887e584-fa86-41ad-9c59-7607d0d2dabd.png)

I'm trying to prepare a reproducible repo.
