### ISSUE TITLE
Wrong S3 bucket name in IAM custom policy for imageLambda execution role

### ISSUE THREAD

**Issue by jackywxd** [serverless-nextjs/serverless-next.js#854] opened 2020-12-26 18:30 UTC
First of all, thanks for making this great project that makes our life so easy!

### Describe the bug
I am new for both Next JS and serverless component. I started play with both with a simple project with one single page and deployed to AWS. During my experimental, I removed and re-deployed the same project couple times. After added couple images using Nextjs 10 new Image component, and those images were missing in the browser and CloudFront returned 500 errors.

### Actual behavior
 After couple hours of debugging, checking previous issues and making sure configuring my project correctly, I realized that the policy of the IAM execution role for the imageLabmda contains a wrong AWS S3 resource.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Resource": "*",
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
            ]
        },
        {
            "Effect": "Allow",
            "Resource": "arn:aws:s3:::w11807j-dqy0qu/*",  <==== Wrong name
            "Action": [
                "s3:GetObject",
                "s3:PutObject"
            ]
        }
    ]
}
```
After change the wrong value to the actual S3 bucket name, update the policy, everything works as expected, images were returned correctly.

### Expected behavior
After each deployment, the correct S3 resource name should be reflected in the corresponding Lambda IAM custom policy correctly.

### Steps to reproduce
Not sure exactly how to re-produce this problem, most likely it was caused by the removed/re-deployed actions.

### Versions
- OS/Environment: macOS Big Sur
- @sls-next/serverless-component version: 1.19.0-alpha.21
- Next.js version: 10.0.4

**Comment by dphang** [comment] 2020-12-27 03:59
Hm, I am not sure why that is happening. Are you using `inputs.roleArn` to set custom role for the Lambdas?

Role is set here: https://github.com/serverless-nextjs/serverless-next.js/blame/f6c5156bf8bb4912528dfb3723227cca0790218a/packages/serverless-components/nextjs-component/src/component.ts#L526-L529 but it looks like for `imageLambda`, we also need to update it so it can use a custom role (looks like a miss on my part, since there was another PR to set roles on default + API lambdas at around same time). If you are using that, it might explain why it is using wrong policy.

**Comment by jackywxd** [comment] 2020-12-27 22:56
@dphang Thanks for the quick response! I did not use inputs.roleArm. Since I am new for both Nextjs and serverless component, I started off the minimum config I copy/paste from the Github. You can find my current config below.

I think I started with the latest version which is 1.18.0, the initial deployment went well, no issue. Then I tried to make some changes, the following deployment failed because of the issue related to error CNAME already exists in Route53. That's when I started remove/deploy couple times with different versions of serverless component. I was able to fix most of the problem, then I realized images were getting error 500 with Nextjs 10 new Image component.

So it might be possible that this problem was caused by the older version of component. And some garbage might be left over during the remove/re-install process.

I suggest we should look into how we update the AWS resource in the custom role and make sure the new resource name updated correctly in IAM policy whenever it is changed.

Thanks again!

```
myNextApplication:
  component: "@sls-next/serverless-component@1.19.0-alpha.21" # it is recommended you pin the latest stable version of serverless-next.js
  inputs:
    domain: "my-domain" # sub-domain defaults to www
    memory:
      imageLambda: 1024
```

**Comment by dphang** [comment] 2020-12-27 23:47
Yes, the image component was only supported in latest alpha version of 1.19. Maybe there is some weird behavior when switching between 1.18 -> 1.19 alpha due to adding a new lambda. Will try to look and see if I can reproduce the same issue.

**Comment by evangow** [comment] 2021-02-10 22:57
@dphang I've specified the roleArn in my serverless.yml, but a new role gets created every time I deploy. In searching, I found that the new role being created is associated with the image lambda, so I don't think the image lambda is using the roleArn set in the serverless.yml file

**Comment by evangow** [comment] 2021-02-10 22:57
BTW, I am using @1.19.0-alpha.30

**Comment by evangow** [comment] 2021-02-11 02:15
@dphang Just had the time to go through the code.

Lines 526-529 of https://github.com/serverless-nextjs/serverless-next.js/blob/%40sls-next/serverless-component%401.19.0-alpha.30/packages/serverless-components/nextjs-component/src/component.ts
```javascript
role: {
    service: ["lambda.amazonaws.com", "edgelambda.amazonaws.com"],
    policy
 }
```

should be:
```javascript
role: inputs.roleArn
    ? {
        arn: inputs.roleArn
    } : {
        service: ["lambda.amazonaws.com", "edgelambda.amazonaws.com"],
        policy
    },
```

The same as it is for the defaultEdgeLambdaInput and the apiEdgeLambdaInput

**Comment by dphang** [comment] 2021-02-11 02:23
Thanks, yeah I had forgotten to update that part as the custom role change was merged around the same time. I can update it tonight.

**Comment by evangow** [comment] 2021-02-11 02:54
Awesome! I greatly appreciate it!

**Comment by dphang** [comment] 2021-02-11 03:17
Cool, closing this then. (The original problem seemed to be due to switching between multiple versions, and this fix should also help the custom role issue. @jackywxd do let us know if you are still facing issues).

**Closed by dphang** 2021-02-11 03:17 UTC
Labels: bug
