### ISSUE TITLE
Rewrites are not working as expected

### ISSUE THREAD

**Issue by jamiechong** [serverless-nextjs/serverless-next.js#815] opened 2020-11-23 21:30 UTC
My next.config.js contains this single rewrite: 
```
  rewrites: async () => [
    {
      source: "/:market(outdoor|leaf|sale)/:rest*",
      destination: "/:rest*?market=:market",
    },
  ],
```

On localhost, if I navigate to `localhost:3000/outdoor/path/to/my-page`, Next will render the page component defined in `pages/path/to/[slug].js`

On an SLS deployed app, I get a 404. 

After deploy the resulting `routes-manifest.json` file contains this relevant rewrite:

```
  "rewrites":[
     {
        "source":"/:market(outdoor|leaf|sale)/:rest*",
        "destination":"/:rest*?market=:market",
        "regex":"^(?:/(outdoor|leaf|sale))(?:/((?:[^/]+?)(?:/(?:[^/]+?))*))?$"
     }
  ],
```

**Comment by dphang** [comment] 2020-11-23 23:35
Please use the bug report template since it allows you to specify the versions you are using - what versions of @sls-next/serverless-component and Next.js are you using?

If still not working after using the latest version (1.18 is the stable one), let me know and I'll try to reproduce it.

**Comment by jamiechong** [comment] 2020-11-24 00:39
Sorry, I tried: 

@sls-next/serverless-component: `1.18.0-alpha.4`, `1.18.0-alpha.19`, and `1.19.0-alpha.10`. 
next: 9.5.5

For context, we also needed to implement a custom component to make things work with the `next-i18next` package we're using. It's so we can export extra static files on the the lambda deploy. The gist is a custom `serverless.js` file. Looks like this: 

```
// https://github.com/serverless-nextjs/serverless-next.js/issues/383

const NextJsComponent = require("@sls-next/serverless-component/serverless");
const fs = require("fs-extra");

class CatalogAppComponent extends NextJsComponent {
  async default(inputs = {}) {
    
    inputs.policy = "...";    
    inputs.bucketName = process.env.SERVERLESS_BUCKET_NAME;
    inputs.name = process.env.SERVERLESS_LAMBDA_NAME;
    inputs.domain = process.env.SERVERLESS_URL_SLUG;
    inputs.build = true;
    inputs.verbose = false;
    
    if (inputs.build !== false) {
      console.log("-> Building...");
      await this.build(inputs);
      console.log("Building was successful");
    }
    console.log("-> Copying locales directory...");
    this.copyLocales();
    console.log("Locale directory was copied successfully");
    console.log("-> Deploying...");
    return this.deploy(inputs);
  }

  copyLocales() {
    const localeSrc = "./public/locales";
    const localeDest = "./.serverless_nextjs/default-lambda/public/locales";
    fs.copySync(localeSrc, localeDest, { recursive: true });
  }
}

module.exports = CatalogAppComponent;
```

**Comment by dphang** [comment] 2020-11-24 00:47
I see, thanks. I'll try to repro later this week, but I just want to make sure the right handler is being copied since you are using the custom component. This code does the rewrite:

https://github.com/serverless-nextjs/serverless-next.js/blob/d03832d83073d88dedfdf99dd7101810ede4c419/packages/libs/lambda-at-edge/src/default-handler.ts#L306-L318

In default-handler folder, is this code being copied to the `index.js` handler (might be slightly different due to transpilation from TS to JS)?

**Comment by dphang** [comment] 2020-11-24 01:14
Ah, it looks like the query params with ? in the destination are not parsed properly, it should be separated and merged with `request.querystring` from the original URI. If you remove the querystring part, I guess it should start working.

**Closed** 2020-11-24 03:23 UTC

**Comment by dphang** [comment] 2020-11-24 03:27
Fixed and published, hopefully it works for you now.

**Comment by jamiechong** [comment] 2020-11-24 18:39
Thanks so much for the quick fix @dphang  - saves me a ton of work-arounds!
